export type SeoServicePage = {
  slug: string;
  title: string;
  description: string;
  eyebrow: string;
  heading: string;
  lead: string;
  problemTitle: string;
  problem: string;
  image: string;
  imageAlt: string;
  imageLabel: string;
  outcomes: Array<{ title: string; text: string }>;
  capabilities: string[];
  idealFor: string[];
  caseStudy?: { name: string; href: string; text: string };
  questions: Array<{ question: string; answer: string }>;
};

export const seoServicePages: SeoServicePage[] = [
  {
    slug: "software-a-la-medida-guadalajara",
    title: "Desarrollo de software a la medida en Guadalajara",
    description: "Creamos software a la medida en Guadalajara para controlar ventas, inventario, clientes, personal, rutas y reportes desde un solo sistema.",
    eyebrow: "Software para empresas en Guadalajara",
    heading: "Un sistema construido alrededor de tu negocio.",
    lead: "Cuando las hojas de cálculo y los programas separados ya no alcanzan, reunimos tu operación en una herramienta clara, segura y preparada para crecer.",
    problemTitle: "Tu forma de trabajar define el sistema",
    problem: "Primero entendemos qué hace tu equipo, dónde se pierde tiempo y qué información necesitas consultar. Después construimos una primera etapa útil, con alcance, calendario y precio por escrito.",
    image: "/portfolio/demos/centro-operativo-demo.svg",
    imageAlt: "Ejemplo de software empresarial con ventas, inventario, clientes y reportes",
    imageLabel: "Ejemplo de solución centralizada",
    outcomes: [
      { title: "Una sola fuente de información", text: "Ventas, clientes, inventario y seguimiento dejan de vivir en archivos separados." },
      { title: "Menos trabajo repetido", text: "Automatizamos capturas, avisos y reportes que hoy consumen tiempo del equipo." },
      { title: "Permisos por usuario", text: "Cada persona ve y modifica únicamente lo necesario para cumplir su función." },
      { title: "Crecimiento por etapas", text: "Comenzamos con lo prioritario y añadimos funciones cuando el negocio las necesita." },
    ],
    capabilities: ["Clientes y seguimiento", "Ventas y cotizaciones", "Inventario y compras", "Cobranza y caja", "Reportes para dirección", "Aplicación móvil", "Documentos y evidencias", "Conexión con herramientas existentes"],
    idealFor: ["Distribuidoras", "Talleres y servicios", "Comercios", "Equipos de campo", "Despachos", "Empresas con procesos propios"],
    caseStudy: { name: "Sana Life", href: "/proyectos/sana-life", text: "Conectamos rutas, ventas, inventario y cobranza en una misma operación." },
    questions: [
      { question: "¿Cuánto cuesta un software a la medida?", answer: "Depende de usuarios, funciones e integraciones. Definimos una primera etapa y entregamos una cotización detallada antes de comenzar." },
      { question: "¿Tengo que saber de tecnología?", answer: "No. Nos explicas cómo trabajas y nosotros convertimos esa operación en funciones claras y prioridades." },
      { question: "¿Puede crecer después?", answer: "Sí. Diseñamos el proyecto por etapas para agregar módulos sin rehacer lo que ya funciona." },
    ],
  },
  {
    slug: "sistemas-de-inventario-y-ventas",
    title: "Sistemas de inventario y ventas para negocios",
    description: "Sistemas de inventario, ventas, compras, caja y cobranza para comercios, distribuidores y talleres en Guadalajara y México.",
    eyebrow: "Inventario y ventas conectados",
    heading: "Conoce qué tienes, qué vendes y cuánto ganas.",
    lead: "Creamos programas que reúnen productos, existencias, ventas, clientes, pagos y utilidad para que tomes decisiones con información actualizada.",
    problemTitle: "Control comercial sin hojas dispersas",
    problem: "El sistema puede adaptarse a una tienda, distribuidora, taller o negocio con ventas a plazos. Cada movimiento actualiza la información que necesita administración.",
    image: "/portfolio/marshop/productos-demo.png",
    imageAlt: "Sistema MarShop con catálogo de productos, costos, precios y existencias",
    imageLabel: "Caso real · MarShop",
    outcomes: [
      { title: "Existencias claras", text: "Consulta productos disponibles, vendidos, apartados o con poco inventario." },
      { title: "Ventas y abonos", text: "Registra pagos completos, ventas a plazos, saldos y próximas fechas de cobro." },
      { title: "Utilidad real", text: "Compara costo, precio, gastos y dinero cobrado para conocer el resultado del negocio." },
      { title: "Catálogo visual", text: "Encuentra productos rápidamente por nombre, categoría, marca, talla o color." },
    ],
    capabilities: ["Productos y fotografías", "Entradas y salidas", "Ventas de contado", "Ventas a plazos", "Agenda de cobros", "Clientes y saldos", "Compras y gastos", "Reportes de utilidad"],
    idealFor: ["Boutiques", "Refaccionarias", "Ferreterías", "Distribuidoras", "Talleres", "Negocios con cobranza"],
    caseStudy: { name: "MarShop", href: "/proyectos/marshop", text: "Un programa para productos, clientas, ventas, abonos, agenda de cobros y finanzas." },
    questions: [
      { question: "¿Puedo usar lector de código de barras?", answer: "Sí. Podemos incluir códigos, búsqueda rápida, etiquetas y flujos de entrada o venta según tu operación." },
      { question: "¿Funciona para varias sucursales?", answer: "Puede prepararse para manejar sucursales, almacenes, usuarios y permisos desde una administración central." },
      { question: "¿Puedo consultar desde mi celular?", answer: "Sí. Podemos crear una versión web adaptable o una aplicación móvil conectada al mismo inventario." },
    ],
  },
  {
    slug: "desarrollo-de-aplicaciones-moviles",
    title: "Desarrollo de aplicaciones móviles en Guadalajara",
    description: "Desarrollo de aplicaciones para iPhone y Android conectadas con ventas, inventario, GPS, clientes y sistemas empresariales.",
    eyebrow: "Aplicaciones para iPhone y Android",
    heading: "Tu operación también puede vivir en el celular.",
    lead: "Diseñamos aplicaciones claras para clientes, vendedores, repartidores y equipos de campo, conectadas con la información central de tu empresa.",
    problemTitle: "Una app con un propósito concreto",
    problem: "No comenzamos por la tecnología. Definimos qué necesita hacer cada persona desde su teléfono y construimos el recorrido más simple para lograrlo.",
    image: "/portfolio/libremente/inicio-anonimo.png",
    imageAlt: "Aplicación móvil LibreMente con actividades de lectura y progreso",
    imageLabel: "Caso real · LibreMente",
    outcomes: [
      { title: "Disponible donde ocurre el trabajo", text: "El equipo consulta, registra y actualiza información sin volver a la oficina." },
      { title: "Experiencia fácil de aprender", text: "Pantallas directas, acciones visibles y textos pensados para usuarios reales." },
      { title: "Información sincronizada", text: "La app comparte ventas, rutas, evidencias o avances con el panel administrativo." },
      { title: "Publicación y soporte", text: "Te acompañamos en pruebas, entrega y evolución de nuevas versiones." },
    ],
    capabilities: ["Inicio de sesión", "Perfiles y permisos", "Notificaciones", "Fotografías y evidencias", "GPS", "Compras o pagos", "Funcionamiento sin conexión", "Panel administrativo"],
    idealFor: ["Equipos de ventas", "Repartidores", "Personal en campo", "Clientes frecuentes", "Educación", "Servicios a domicilio"],
    caseStudy: { name: "LibreMente", href: "/proyectos/libremente", text: "Aplicación educativa con biblioteca, actividades, metas y seguimiento del aprendizaje." },
    questions: [
      { question: "¿Desarrollan para iPhone y Android?", answer: "Sí. Definimos la mejor opción según las funciones, el presupuesto y los dispositivos de tus usuarios." },
      { question: "¿La aplicación puede conectarse con mi sistema?", answer: "Sí. La app puede compartir clientes, productos, pedidos, ubicaciones y reportes con tu administración central." },
      { question: "¿También ayudan a publicarla?", answer: "Podemos contemplar preparación, pruebas y acompañamiento para su distribución según el alcance acordado." },
    ],
  },
  {
    slug: "gps-y-mapas-en-vivo",
    title: "Software con GPS y mapas en vivo para empresas",
    description: "Software con GPS, mapas en vivo, rutas, paradas, evidencias y alertas para personal, reparto y operaciones en campo.",
    eyebrow: "Ubicación y operación en campo",
    heading: "Mira dónde está tu operación y qué está sucediendo.",
    lead: "Integramos mapas, ubicación, rutas, jornadas y evidencias para que supervises equipos de campo desde una sola pantalla.",
    problemTitle: "Ubicación con contexto, no sólo un punto en el mapa",
    problem: "Además de recibir una posición, el sistema puede mostrar qué trabajador está activo, cuál es su ruta, cuándo envió evidencia y qué incidencia requiere atención.",
    image: "/portfolio/geojornada/mapa-operativo-demo.webp",
    imageAlt: "Sistema GeoJornada con mapa GPS y ubicación de personal en vivo",
    imageLabel: "Caso real · GeoJornada",
    outcomes: [
      { title: "Última ubicación recibida", text: "Identifica posiciones recientes y distingue señales antiguas para evitar conclusiones equivocadas." },
      { title: "Rutas y paradas", text: "Consulta recorrido, lugares asignados y avance del trabajo durante la jornada." },
      { title: "Evidencia verificable", text: "Relaciona fotografías, referencias, fecha y ubicación con cada visita realizada." },
      { title: "Alertas operativas", text: "Detecta atrasos, incidencias o falta de señal para actuar a tiempo." },
    ],
    capabilities: ["Mapa en vivo", "Historial de recorridos", "Velocidad y batería", "Rutas y paradas", "Geocercas", "Fotografías", "Alertas", "Panel de supervisión"],
    idealFor: ["Reparto", "Ventas en campo", "Supervisión", "Instalaciones", "Mantenimiento", "Visitas a clientes"],
    caseStudy: { name: "GeoJornada", href: "/proyectos/geojornada", text: "Control de jornadas, ubicaciones y evidencias para personal que trabaja fuera de oficina." },
    questions: [
      { question: "¿La ubicación se actualiza en tiempo real?", answer: "La frecuencia depende del dispositivo, conexión y operación. Mostramos siempre la hora de la última señal para mantener claridad." },
      { question: "¿Puedo revisar recorridos anteriores?", answer: "Sí. El sistema puede conservar historial, paradas, evidencias e incidencias según el periodo acordado." },
      { question: "¿Funciona con celulares del personal?", answer: "Sí. Podemos utilizar una aplicación instalada en los dispositivos autorizados por la empresa y sus trabajadores." },
    ],
  },
  {
    slug: "control-de-personal",
    title: "Software para control de personal y trabajadores en campo",
    description: "Sistema para controlar jornadas, asistencia, ubicaciones, actividades y evidencias de trabajadores en campo desde un panel central.",
    eyebrow: "Personal y jornadas bajo control",
    heading: "Cada jornada deja información clara y comprobable.",
    lead: "Ayudamos a coordinar trabajadores, horarios, lugares asignados, actividades y evidencias sin depender de mensajes dispersos.",
    problemTitle: "Supervisión clara para oficina y campo",
    problem: "El trabajador registra desde su celular y administración consulta desde un panel. Así cada jornada conserva horarios, ubicación, actividad y evidencia en un mismo expediente.",
    image: "/portfolio/geojornada/evidencia-movil-demo.webp",
    imageAlt: "Aplicación de GeoJornada para registrar evidencia de trabajo con ubicación",
    imageLabel: "Caso real · GeoJornada",
    outcomes: [
      { title: "Entradas y salidas", text: "Registra el inicio y cierre de jornada con las validaciones necesarias para tu negocio." },
      { title: "Asignaciones visibles", text: "Cada persona conoce su lugar, horario, actividad y prioridad del día." },
      { title: "Evidencias organizadas", text: "Fotografías, notas y referencias quedan ligadas a la jornada correspondiente." },
      { title: "Reportes para supervisión", text: "Consulta cumplimiento, incidencias y actividad por trabajador o periodo." },
    ],
    capabilities: ["Expedientes de personal", "Horarios y jornadas", "Ubicación autorizada", "Asignación de lugares", "Fotografías y notas", "Incidencias", "Alertas", "Reportes por periodo"],
    idealFor: ["Promotores", "Instaladores", "Técnicos", "Supervisores", "Repartidores", "Equipos de visita"],
    caseStudy: { name: "GeoJornada", href: "/proyectos/geojornada", text: "Una solución real para jornadas, ubicación operativa, evidencias e historial." },
    questions: [
      { question: "¿El trabajador necesita un equipo especial?", answer: "En muchos casos puede usar un celular autorizado. Revisamos compatibilidad, conexión y políticas internas antes de definir la solución." },
      { question: "¿Se puede limitar la ubicación al horario laboral?", answer: "Sí. El diseño puede respetar horarios, permisos y avisos claros para el uso responsable de ubicación." },
      { question: "¿Puedo exportar reportes?", answer: "Sí. Podemos incluir consultas por fecha, trabajador, lugar o incidencia y generar archivos para administración." },
    ],
  },
  {
    slug: "sistema-punto-de-venta",
    title: "Sistema de punto de venta para negocios",
    description: "Desarrollamos sistemas de punto de venta con caja, productos, inventario, clientes, cortes y reportes para comercios en Guadalajara y México.",
    eyebrow: "Punto de venta y caja",
    heading: "Vende rápido y mantén cada movimiento bajo control.",
    lead: "Reunimos caja, productos, existencias, clientes y resultados del día en un programa fácil de usar para tu equipo.",
    problemTitle: "La venta actualiza todo lo demás",
    problem: "Al registrar una venta, el sistema puede descontar existencias, guardar el método de pago, actualizar caja y dejar la información lista para tus reportes.",
    image: "/portfolio/marshop/ventas-demo.png",
    imageAlt: "Sistema MarShop con ventas, saldos, estados y seguimiento de cobros",
    imageLabel: "Caso real · MarShop",
    outcomes: [
      { title: "Cobro más ágil", text: "Encuentra productos, calcula totales y registra diferentes formas de pago desde una sola pantalla." },
      { title: "Caja clara", text: "Consulta entradas, salidas, ventas y cortes por usuario, turno o fecha." },
      { title: "Inventario actualizado", text: "Cada venta afecta las existencias para ayudarte a detectar faltantes y necesidades de compra." },
      { title: "Información para decidir", text: "Conoce qué se vende, en qué horario y cuál es el resultado real del negocio." },
    ],
    capabilities: ["Ventas y devoluciones", "Caja y cortes", "Productos y códigos", "Inventario", "Clientes", "Usuarios y permisos", "Tickets", "Reportes"],
    idealFor: ["Tiendas", "Boutiques", "Ferreterías", "Refaccionarias", "Papelerías", "Comercios con mostrador"],
    caseStudy: { name: "MarShop", href: "/proyectos/marshop", text: "Un programa real para productos, clientas, ventas, abonos, agenda de cobros y finanzas." },
    questions: [
      { question: "¿Se puede usar con lector de códigos e impresora?", answer: "Sí. Revisamos los equipos que ya tienes y definimos qué lectores, impresoras o cajones se conectarán al sistema." },
      { question: "¿Funciona sin internet?", answer: "Podemos diseñar una solución local o con funcionamiento temporal sin conexión, según cuántas cajas, sucursales y usuarios necesites." },
      { question: "¿Puede emitir facturas?", answer: "Puede conectarse con un proveedor de facturación autorizado. Esa integración y sus costos se especifican en la propuesta." },
    ],
  },
  {
    slug: "crm-para-empresas",
    title: "CRM a la medida para empresas y ventas",
    description: "CRM para organizar prospectos, clientes, oportunidades, cotizaciones, actividades y seguimiento comercial en un solo sistema.",
    eyebrow: "Clientes y seguimiento comercial",
    heading: "Ninguna oportunidad se pierde entre mensajes y hojas de cálculo.",
    lead: "Construimos un CRM adaptado a tu proceso para que ventas conozca el siguiente paso y dirección pueda revisar el avance comercial.",
    problemTitle: "Tu proceso de venta, visible para todo el equipo",
    problem: "Cada contacto conserva responsable, etapa, conversaciones, tareas y documentos. Así el seguimiento continúa aunque intervengan varias personas.",
    image: "/portfolio/demos/crm-profesional-demo.svg",
    imageAlt: "Ejemplo de CRM con prospectos, oportunidades y seguimiento comercial",
    imageLabel: "Solución posible · CRM comercial",
    outcomes: [
      { title: "Seguimiento ordenado", text: "Cada vendedor sabe a quién contactar, qué se acordó y cuál es la próxima actividad." },
      { title: "Proceso comercial visible", text: "Consulta oportunidades nuevas, en seguimiento, cotizadas, ganadas o perdidas." },
      { title: "Historial por cliente", text: "Centraliza notas, llamadas, cotizaciones, archivos y responsables." },
      { title: "Pronóstico más real", text: "Mide avance, tiempos de respuesta y valor esperado sin pedir reportes manuales." },
    ],
    capabilities: ["Prospectos", "Directorio de clientes", "Etapas de venta", "Tareas y recordatorios", "Cotizaciones", "Historial", "Permisos", "Indicadores"],
    idealFor: ["Equipos comerciales", "Distribuidoras", "Despachos", "Servicios B2B", "Inmobiliarias", "Ventas por seguimiento"],
    questions: [
      { question: "¿Puede adaptarse a nuestras etapas de venta?", answer: "Sí. Configuramos etapas, responsables, datos y reglas alrededor de la forma real en que vende tu empresa." },
      { question: "¿Se puede importar información existente?", answer: "Podemos revisar tus archivos actuales, limpiar los datos y definir una importación segura dentro del alcance." },
      { question: "¿Se conecta con WhatsApp o correo?", answer: "Es posible integrar canales y automatizaciones según permisos, proveedores disponibles y necesidades del equipo." },
    ],
  },
  {
    slug: "software-para-talleres",
    title: "Software para talleres, reparaciones y servicios",
    description: "Software para talleres con clientes, equipos, diagnósticos, cotizaciones, refacciones, evidencias, inventario y seguimiento de reparaciones.",
    eyebrow: "Talleres y órdenes de servicio",
    heading: "Cada equipo, diagnóstico y reparación en un solo expediente.",
    lead: "Organiza la recepción, cotización, autorización, reparación, piezas utilizadas, pagos y entrega sin depender de notas sueltas.",
    problemTitle: "Seguimiento claro desde que el equipo entra hasta que sale",
    problem: "El personal consulta el estado de cada servicio y el cliente recibe información más clara. Administración conserva costos, evidencias y responsables.",
    image: "/portfolio/cellgo/panel-administrativo.png",
    imageAlt: "Panel de CellGo para ventas, inventario y reparaciones de celulares",
    imageLabel: "Caso real · CellGo",
    outcomes: [
      { title: "Recepción completa", text: "Registra cliente, equipo, condición, accesorios, falla reportada y fotografías." },
      { title: "Estados visibles", text: "Identifica servicios recibidos, en diagnóstico, autorizados, en reparación o listos para entrega." },
      { title: "Piezas y costos", text: "Relaciona refacciones, mano de obra, anticipos y saldo con la orden correspondiente." },
      { title: "Historial confiable", text: "Consulta reparaciones anteriores, garantías, técnicos y comunicaciones con el cliente." },
    ],
    capabilities: ["Órdenes de servicio", "Diagnóstico", "Cotizaciones", "Evidencias", "Inventario de piezas", "Técnicos", "Pagos", "Garantías"],
    idealFor: ["Talleres de celulares", "Servicio técnico", "Mantenimiento", "Electrónica", "Reparación de equipos", "Centros de servicio"],
    caseStudy: { name: "CellGo", href: "/proyectos/cellgo", text: "Una operación real con reparaciones, clientes, ventas, inventario y comercio electrónico." },
    questions: [
      { question: "¿Puedo avisar al cliente cuando su equipo esté listo?", answer: "Sí. Podemos incluir avisos y plantillas según el canal de comunicación definido para el taller." },
      { question: "¿Controla refacciones y mano de obra?", answer: "Sí. Cada servicio puede relacionar piezas utilizadas, costos, precio de reparación, anticipo y saldo." },
      { question: "¿Sirve para más de una sucursal?", answer: "Puede manejar sucursales, técnicos, almacenes y permisos desde una administración central." },
    ],
  },
  {
    slug: "sistemas-para-distribuidoras",
    title: "Sistemas para distribuidoras, rutas y reparto",
    description: "Sistemas para distribuidoras con inventario, pedidos, ventas, rutas, reparto, cobranza y control de vendedores desde una operación central.",
    eyebrow: "Distribución, rutas y cobranza",
    heading: "Del almacén a la entrega, toda la operación conectada.",
    lead: "Integramos pedidos, productos, vendedores, rutas, entregas y cobros para que oficina y campo trabajen con la misma información.",
    problemTitle: "Un pedido visible de principio a fin",
    problem: "Administración prepara la operación y el equipo de campo actualiza avances desde su celular. Cada entrega conserva productos, importe, evidencia y estado de cobro.",
    image: "/portfolio/sana-life/mapa-en-vivo-demo.svg",
    imageAlt: "Sistema de Sana Life para rutas, reparto y ubicación operativa",
    imageLabel: "Caso real · Sana Life",
    outcomes: [
      { title: "Pedidos organizados", text: "Agrupa productos, clientes, fechas y prioridades antes de preparar cada salida." },
      { title: "Rutas con avance", text: "Consulta repartidores, paradas, entregas realizadas y pendientes del día." },
      { title: "Inventario conectado", text: "Relaciona almacén, carga de unidad, entrega y devolución para mantener claridad." },
      { title: "Cobranza en campo", text: "Registra efectivo, transferencia, crédito y saldo directamente en la visita." },
    ],
    capabilities: ["Pedidos", "Inventario", "Carga de unidades", "Rutas", "Aplicación para reparto", "Evidencias", "Cobranza", "Reportes"],
    idealFor: ["Distribuidoras", "Mayoristas", "Reparto local", "Alimentos", "Insumos", "Productos veterinarios"],
    caseStudy: { name: "Sana Life", href: "/proyectos/sana-life", text: "Sistema conectado para productos veterinarios, rutas, entregas, ubicación y cobranza." },
    questions: [
      { question: "¿El repartidor puede cobrar desde la aplicación?", answer: "Puede registrar forma de pago, importe, saldo y evidencia para que administración vea el resultado de la visita." },
      { question: "¿Se pueden planear rutas?", answer: "Sí. Podemos ordenar paradas, asignar unidades y mostrar avance o última ubicación recibida." },
      { question: "¿Controla inventario por vehículo?", answer: "Puede manejar almacenes, cargas, devoluciones y existencias por unidad según el nivel de control requerido." },
    ],
  },
  {
    slug: "automatizacion-de-procesos",
    title: "Automatización de procesos para empresas",
    description: "Automatizamos capturas, cálculos, documentos, aprobaciones, avisos y reportes para reducir trabajo repetitivo y errores en empresas.",
    eyebrow: "Menos tareas repetitivas",
    heading: "Convierte procesos manuales en recorridos claros y medibles.",
    lead: "Si tu equipo captura lo mismo varias veces, calcula en hojas separadas o prepara reportes manualmente, podemos reunir y automatizar ese trabajo.",
    problemTitle: "Primero simplificamos; después automatizamos",
    problem: "Revisamos entradas, decisiones, responsables y resultados. El objetivo no es añadir pasos digitales, sino eliminar repeticiones y dejar trazabilidad.",
    image: "/portfolio/planifica40/escenarios-anonimos.png",
    imageAlt: "Planifica40 con cálculos de escenarios y generación de reportes",
    imageLabel: "Caso real · Planifica40",
    outcomes: [
      { title: "Captura una sola vez", text: "La información se reutiliza en cálculos, documentos, avisos y consultas autorizadas." },
      { title: "Reglas consistentes", text: "El sistema aplica validaciones y cálculos de la misma forma para cada operación." },
      { title: "Documentos automáticos", text: "Genera cotizaciones, reportes, comprobantes o archivos a partir de datos revisados." },
      { title: "Seguimiento medible", text: "Cada etapa conserva fecha, responsable, estado y resultado para detectar retrasos." },
    ],
    capabilities: ["Formularios", "Validaciones", "Cálculos", "Aprobaciones", "Alertas", "Generación de PDF", "Exportación", "Panel de seguimiento"],
    idealFor: ["Administración", "Finanzas", "Ventas", "Recursos humanos", "Operaciones", "Despachos especializados"],
    caseStudy: { name: "Planifica40", href: "/proyectos/planifica40", text: "Lectura de información, cálculos avanzados, comparación de escenarios y generación de reportes para clientes." },
    questions: [
      { question: "¿Qué procesos se pueden automatizar?", answer: "Procesos con pasos repetibles, datos definidos, cálculos, aprobaciones, documentos o avisos suelen ser buenos candidatos." },
      { question: "¿Se elimina por completo el trabajo humano?", answer: "No necesariamente. Automatizamos lo repetitivo y conservamos decisiones o revisiones humanas donde aportan seguridad y criterio." },
      { question: "¿Puede conectarse con mis archivos actuales?", answer: "Revisamos formatos y calidad de datos para definir importaciones, exportaciones o integraciones seguras." },
    ],
  },
  {
    slug: "servidores-y-respaldos-para-empresas",
    title: "Servidores, respaldos e integraciones para empresas",
    description: "Configuración de servidores, respaldos, bases de datos e integraciones para mantener sistemas empresariales disponibles, conectados y protegidos.",
    eyebrow: "Infraestructura para tu operación",
    heading: "La base que mantiene tus sistemas conectados y disponibles.",
    lead: "Configuramos la infraestructura necesaria para que aplicaciones, usuarios, información y respaldos trabajen con continuidad.",
    problemTitle: "Infraestructura adecuada al tamaño del negocio",
    problem: "Podemos trabajar con una computadora preparada como servidor local, servicios en la nube o una combinación de ambos. La elección depende de usuarios, conexión, seguridad y crecimiento esperado.",
    image: "/portfolio/demos/centro-operativo-demo.svg",
    imageAlt: "Ejemplo de operación empresarial conectada con información central",
    imageLabel: "Ejemplo de solución · operación conectada",
    outcomes: [
      { title: "Información central", text: "Las aplicaciones autorizadas consultan la misma base para evitar versiones contradictorias." },
      { title: "Respaldos definidos", text: "Establecemos frecuencia, conservación y recuperación según la importancia de la información." },
      { title: "Accesos controlados", text: "Usuarios, permisos y conexiones se configuran de acuerdo con las responsabilidades del equipo." },
      { title: "Base para crecer", text: "La infraestructura puede evolucionar conforme aumentan usuarios, sucursales o aplicaciones." },
    ],
    capabilities: ["Servidor Linux", "Servidor local", "Nube", "Base de datos", "Respaldos", "Acceso seguro", "Integraciones", "Monitoreo"],
    idealFor: ["Sistemas internos", "Varias sucursales", "Aplicaciones móviles", "Equipos remotos", "Operaciones críticas", "Empresas en crecimiento"],
    questions: [
      { question: "¿Necesito comprar un servidor?", answer: "No siempre. Revisamos usuarios, conexión y uso para elegir entre equipo local, nube o una solución combinada." },
      { question: "¿Pueden configurar Linux en una computadora del negocio?", answer: "Sí, cuando es adecuado para la operación. Evaluamos el equipo, la red, los respaldos y la forma de recuperación antes de instalar." },
      { question: "¿Incluye mantenimiento?", answer: "Podemos definir monitoreo, respaldos y soporte periódico como un servicio separado del desarrollo inicial." },
    ],
  },
];

export const seoServiceBySlug = Object.fromEntries(seoServicePages.map((page) => [page.slug, page]));
